apiVersion: v1
kind: Pod
metadata:
  name: spring-test-app
  labels:
    app: spring-test-app
spec:
  containers:
  - name: spring-app
    image: REPLACE
    ports:
    - name: some-port
      containerPort: 80
      protocol: TCP